```properties
spring.application.name=MyProject

# SQL Server DataSource
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Computer;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Hoang24102005@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=c2lsdmVyc3ByaW5nYm9vdG5vcm1hbHNlY3VyZWtleW11c3RiZWxvbmc0NTY3ODkwMTIzNDU2Nzg5MDEy

# 1 phút = 60000 milliseconds
jwt.expiration=60000

# 7 ngày = 604800000 milliseconds
jwt.refresh-expiration=604800000
```
